export enum BandeiraCartao {
  MASTERCARD = 'MASTERCARD',

  VISA = 'VISA',

  AMERICAN_EXPRESS = 'AMERICAN_EXPRESS',

  ELO = 'ELO',

  DISCOVER_NETWORK = 'DISCOVER_NETWORK',

  HIPERCARD = 'HIPERCARD',

  DINERS_CLUB = 'DINERS_CLUB',

  OUTRO = 'OUTRO',
}
